2024-02-29 19:01:12,139 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:01:12,139 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Configure stats pid to 12792
2024-02-29 19:01:12,139 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:01:12,139 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:01:12,140 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:01:12,140 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190112-bmxh95lu\logs\debug.log
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190112-bmxh95lu\logs\debug-internal.log
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 391}
2024-02-29 19:01:12,141 INFO    MainThread:12792 [wandb_init.py:init():616] starting backend
2024-02-29 19:01:12,142 INFO    MainThread:12792 [wandb_init.py:init():620] setting up manager
2024-02-29 19:01:12,148 INFO    MainThread:12792 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:01:12,149 INFO    MainThread:12792 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:01:12,169 INFO    MainThread:12792 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:01:12,169 INFO    MainThread:12792 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:01:12,169 INFO    MainThread:12792 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:01:12,214 INFO    MainThread:12792 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:01:31,348 ERROR   MainThread:12792 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 19:01:31,415 ERROR   MainThread:12792 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 19:02:48,325 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:02:48,326 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Configure stats pid to 12792
2024-02-29 19:02:48,326 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:02:48,326 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:02:48,326 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:02:48,326 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:02:48,327 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:02:48,327 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-02-29 19:02:48,327 INFO    MainThread:12792 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190248-q2qi51wo\logs\debug.log
2024-02-29 19:02:48,327 INFO    MainThread:12792 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190248-q2qi51wo\logs\debug-internal.log
2024-02-29 19:02:48,328 INFO    MainThread:12792 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:02:48,328 INFO    MainThread:12792 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 391}
2024-02-29 19:02:48,328 INFO    MainThread:12792 [wandb_init.py:init():616] starting backend
2024-02-29 19:02:48,328 INFO    MainThread:12792 [wandb_init.py:init():620] setting up manager
2024-02-29 19:02:48,338 INFO    MainThread:12792 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:02:48,338 INFO    MainThread:12792 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:02:48,355 INFO    MainThread:12792 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:02:48,355 INFO    MainThread:12792 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:02:48,356 INFO    MainThread:12792 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:02:48,399 INFO    MainThread:12792 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:04:18,970 ERROR   MainThread:12792 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:04:19,724 ERROR   MainThread:12792 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:06:55,008 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:06:55,008 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Configure stats pid to 12792
2024-02-29 19:06:55,008 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:06:55,009 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:06:55,009 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:06:55,009 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:06:55,010 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:06:55,010 INFO    MainThread:12792 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-02-29 19:06:55,010 INFO    MainThread:12792 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190654-s0t8dejl\logs\debug.log
2024-02-29 19:06:55,010 INFO    MainThread:12792 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190654-s0t8dejl\logs\debug-internal.log
2024-02-29 19:06:55,011 INFO    MainThread:12792 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:06:55,011 INFO    MainThread:12792 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 391}
2024-02-29 19:06:55,011 INFO    MainThread:12792 [wandb_init.py:init():616] starting backend
2024-02-29 19:06:55,011 INFO    MainThread:12792 [wandb_init.py:init():620] setting up manager
2024-02-29 19:06:55,018 INFO    MainThread:12792 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:06:55,019 INFO    MainThread:12792 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:06:55,033 INFO    MainThread:12792 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:06:55,033 INFO    MainThread:12792 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:06:55,033 INFO    MainThread:12792 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:06:55,076 INFO    MainThread:12792 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:06:56,084 WARNING MsgRouterThr:12792 [router.py:message_loop():77] message_loop has been closed
2024-02-29 19:08:25,638 ERROR   MainThread:12792 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:08:25,785 ERROR   MainThread:12792 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:08:57,649 WARNING MsgRouterThr:12792 [router.py:message_loop():77] message_loop has been closed
2024-02-29 19:08:57,649 WARNING MsgRouterThr:12792 [router.py:message_loop():77] message_loop has been closed
2024-02-29 19:08:57,649 WARNING MsgRouterThr:12792 [router.py:message_loop():77] message_loop has been closed
