2024-02-29 19:09:15,346 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:09:15,346 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Configure stats pid to 9116
2024-02-29 19:09:15,346 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:09:15,346 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:09:15,346 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:09:15,346 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190915-c5ofvcwe\logs\debug.log
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_190915-c5ofvcwe\logs\debug-internal.log
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000148CA641950>
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 733}
2024-02-29 19:09:15,347 INFO    MainThread:9116 [wandb_init.py:init():616] starting backend
2024-02-29 19:09:15,348 INFO    MainThread:9116 [wandb_init.py:init():620] setting up manager
2024-02-29 19:09:15,357 INFO    MainThread:9116 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:09:15,360 INFO    MainThread:9116 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:09:15,375 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:09:15,376 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:09:15,376 INFO    MainThread:9116 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:09:15,419 INFO    MainThread:9116 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:09:16,425 ERROR   MainThread:9116 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 19:09:17,059 ERROR   MainThread:9116 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 19:11:16,851 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:11:16,851 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Configure stats pid to 9116
2024-02-29 19:11:16,851 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:11:16,851 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:11:16,851 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:11:16,851 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:11:16,852 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:11:16,853 INFO    MainThread:9116 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_191116-lguk457x\logs\debug.log
2024-02-29 19:11:16,853 INFO    MainThread:9116 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_191116-lguk457x\logs\debug-internal.log
2024-02-29 19:11:16,853 INFO    MainThread:9116 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:11:16,854 INFO    MainThread:9116 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 733}
2024-02-29 19:11:16,854 INFO    MainThread:9116 [wandb_init.py:init():616] starting backend
2024-02-29 19:11:16,854 INFO    MainThread:9116 [wandb_init.py:init():620] setting up manager
2024-02-29 19:11:16,863 INFO    MainThread:9116 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:11:16,864 INFO    MainThread:9116 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:11:16,881 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:11:16,881 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:11:16,881 INFO    MainThread:9116 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:11:16,926 INFO    MainThread:9116 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:11:17,931 ERROR   MainThread:9116 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 19:11:18,027 ERROR   MainThread:9116 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-29 19:16:31,815 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:16:31,816 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Configure stats pid to 9116
2024-02-29 19:16:31,816 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:16:31,816 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:16:31,816 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:16:31,816 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:16:31,817 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:16:31,817 INFO    MainThread:9116 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_191631-jjeo5fjr\logs\debug.log
2024-02-29 19:16:31,817 INFO    MainThread:9116 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_191631-jjeo5fjr\logs\debug-internal.log
2024-02-29 19:16:31,817 INFO    MainThread:9116 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:16:31,817 INFO    MainThread:9116 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 733}
2024-02-29 19:16:31,817 INFO    MainThread:9116 [wandb_init.py:init():616] starting backend
2024-02-29 19:16:31,818 INFO    MainThread:9116 [wandb_init.py:init():620] setting up manager
2024-02-29 19:16:31,825 INFO    MainThread:9116 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:16:31,826 INFO    MainThread:9116 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:16:31,840 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:16:31,840 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:16:31,840 INFO    MainThread:9116 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:16:31,885 INFO    MainThread:9116 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:18:02,568 ERROR   MainThread:9116 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:18:02,712 ERROR   MainThread:9116 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:23:05,366 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 19:23:05,367 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Configure stats pid to 9116
2024-02-29 19:23:05,367 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2024-02-29 19:23:05,367 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\settings
2024-02-29 19:23:05,367 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-29 19:23:05,367 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 19:23:05,368 INFO    MainThread:9116 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 19:23:05,368 INFO    MainThread:9116 [wandb_init.py:_log_setup():526] Logging user logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_192305-1sqhxp4b\logs\debug.log
2024-02-29 19:23:05,368 INFO    MainThread:9116 [wandb_init.py:_log_setup():527] Logging internal logs to D:\Study\Skoltech\MachineLearning\ts_robustness\notebooks\wandb\run-20240229_192305-1sqhxp4b\logs\debug-internal.log
2024-02-29 19:23:05,369 INFO    MainThread:9116 [wandb_init.py:init():566] calling init triggers
2024-02-29 19:23:05,369 INFO    MainThread:9116 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'model': {'encoder': {'d_model': 50, 'nhead': 25, 'layer_norm_eps': 0.001, 'dropout': 0.5}, 'num_layers': 2, 'fc': {'dim': 50, 'dropout': 0.5}}, 'train': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0003, 'n_epoch': 2}, 'random_state': 733}
2024-02-29 19:23:05,369 INFO    MainThread:9116 [wandb_init.py:init():616] starting backend
2024-02-29 19:23:05,369 INFO    MainThread:9116 [wandb_init.py:init():620] setting up manager
2024-02-29 19:23:05,377 INFO    MainThread:9116 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 19:23:05,378 INFO    MainThread:9116 [wandb_init.py:init():628] backend started and connected
2024-02-29 19:23:05,395 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 19:23:05,395 INFO    MainThread:9116 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 19:23:05,395 INFO    MainThread:9116 [wandb_init.py:init():720] updated telemetry
2024-02-29 19:23:05,437 INFO    MainThread:9116 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 19:24:36,254 ERROR   MainThread:9116 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:24:37,002 ERROR   MainThread:9116 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 19:24:45,166 WARNING MsgRouterThr:9116 [router.py:message_loop():77] message_loop has been closed
2024-02-29 19:24:45,167 WARNING MsgRouterThr:9116 [router.py:message_loop():77] message_loop has been closed
2024-02-29 19:24:45,167 WARNING MsgRouterThr:9116 [router.py:message_loop():77] message_loop has been closed
2024-02-29 19:24:45,167 WARNING MsgRouterThr:9116 [router.py:message_loop():77] message_loop has been closed
